#!/bin/bash

GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo ${GREEN}Enter name of project folder to be created:${NC}
read -p "${PWD}/" foo
mkdir "$foo" && cd "$foo"
composer require laravel/homestead --dev
php vendor/bin/homestead make
read -p $'\e[0;32mContinue and install WordPress?\e[0m [\e[1;33mY,n\e[0m]? \e[0m' -r
echo    # (optional) move to a new line
if [[ ${REPLY} =~ ^[Yy]$ ]] || [[ -z ${REPLY} ]]
then
  git clone --depth=1 git@github.com:WordPress/WordPress.git public && rm -rf public/.git
fi

